In [10]:
import torch
import torch.nn as nn

In [2]:
a = torch.arange(10).reshape(5,2)
print(a)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [8]:
print(torch.split(a, 3, dim=0))

(tensor([[0, 1],
        [2, 3],
        [4, 5]]), tensor([[6, 7],
        [8, 9]]))


In [11]:
pixel_shuffle = nn.PixelShuffle(3)

In [12]:
input = torch.randn(1, 9, 4, 4)
print(input)

tensor([[[[-5.7213e-01, -7.6117e-01, -6.3839e-01, -1.1969e+00],
          [ 9.4826e-01,  9.3392e-01,  1.6019e+00, -5.5526e-01],
          [ 1.8063e+00,  1.0083e+00, -1.9026e-01, -1.3563e+00],
          [ 1.2393e-01,  1.1140e+00, -1.9570e+00, -3.7912e-01]],

         [[ 1.1038e-01, -1.9837e-01,  1.2758e+00, -4.4068e-01],
          [ 2.5016e+00, -1.3928e+00, -3.7290e-01,  1.9451e-01],
          [ 1.4370e+00, -1.4959e+00, -2.2079e+00, -6.6058e-02],
          [-9.4426e-01, -1.4239e+00, -4.9126e-02, -1.1300e-01]],

         [[-1.5434e+00,  1.4061e+00,  1.2569e+00,  1.2474e+00],
          [ 1.1052e+00,  2.4525e+00,  5.9593e-01, -1.1293e+00],
          [ 9.4641e-01,  4.5515e-01, -1.9246e-01, -1.0839e-01],
          [ 2.6087e-01,  2.6745e+00, -3.7039e-01,  1.5306e+00]],

         [[ 2.4145e-03,  2.0818e-01,  1.0286e+00, -3.6510e-01],
          [-1.8065e-01,  7.7196e-02, -9.4542e-03,  8.1005e-01],
          [ 1.7170e+00,  1.3672e+00, -3.1059e-01, -8.9158e-01],
          [-1.6311e+00, -5.5516e-0

In [13]:
output = pixel_shuffle(input)
print(output)

tensor([[[[-5.7213e-01,  1.1038e-01, -1.5434e+00, -7.6117e-01, -1.9837e-01,
            1.4061e+00, -6.3839e-01,  1.2758e+00,  1.2569e+00, -1.1969e+00,
           -4.4068e-01,  1.2474e+00],
          [ 2.4145e-03,  2.7102e+00,  1.3325e-01,  2.0818e-01,  4.7148e-01,
            5.9668e-01,  1.0286e+00,  3.5722e-01, -8.5587e-01, -3.6510e-01,
            5.1741e-01, -4.5058e-01],
          [-4.9069e-01, -1.3394e+00, -1.7089e+00, -6.9161e-02,  3.1604e-01,
           -8.4175e-02, -3.6507e-01, -5.6857e-01, -1.0629e+00, -2.8955e-01,
            4.1196e-01,  7.8637e-01],
          [ 9.4826e-01,  2.5016e+00,  1.1052e+00,  9.3392e-01, -1.3928e+00,
            2.4525e+00,  1.6019e+00, -3.7290e-01,  5.9593e-01, -5.5526e-01,
            1.9451e-01, -1.1293e+00],
          [-1.8065e-01, -2.4206e-01,  3.7045e-01,  7.7196e-02, -1.1085e+00,
            2.8217e-01, -9.4542e-03,  6.7073e-01, -3.0067e-01,  8.1005e-01,
           -4.8457e-01, -1.9478e+00],
          [ 1.1555e+00,  7.2120e-01,  3.7153e-01, 

In [ ]:
|